### ISSUE TITLE
Tera Finder Plugin Window

### ISSUE THREAD

**Issue by Joseph11024** [Manu098vm/Tera-Finder#48]
Hey didn't know where else to bring this up at or if you are already aware of the issue. Anyways When I open tera finder plugin through PKHeX and open the Raid Calculator the right side of the window is cut off.  (See attachments) 

![Screenshot 2023-06-25 112400](https://github.com/Manu098vm/Tera-Finder/assets/83472295/c4e58eb8-7cb7-4d4e-81d1-ba29c3f47444)

The part where you select the Ability, Nature, Gender and Shininess. You cannot view the dropdown menu because it is cut off. At first I didn't think it was a big deal because I could click on the box and just type in what I wanted. However after testing even with correct capitalization and everything when I select apply filters it does not apply the filters from the cutoff section that are typed manually. Just wondering if that was a bug or if there was something I had to do on my end to be able to view the entire window. 

The stand alone program works great and I'm able to view and use the entire window no issues. 

![Screenshot 2023-06-25 112509](https://github.com/Manu098vm/Tera-Finder/assets/83472295/8aae549f-06fb-4c7f-9854-46f5396424d2)

**Comment by Manu098vm** [comment]
When Tera Finder is loaded by PKHeX, the Window Scaling is handled by PKHeX itself. I don't really have a proper fix to this, other than reduing the size of all the control elements. I feel like this would break the view on other monitor resolutions though. 
Since this seems to be an issue only on a niche part of monitors, I feel like it's better for the impacted users to just use the Tera Finder Launcher instead of the PKHeX Plugins. Eventually users can also adjust the Scale settings for PKHeX itself, which would also have an effect to the Tera Finder plugins.

**Comment by Joseph11024** [comment]
Ok thanks I appreciate it 👍Sent from my iPhoneOn Jun 25, 2023, at 5:38 PM, Manu ***@***.***> wrote:﻿
When Tera Finder is loaded by PKHeX, the Window Scaling is handled by PKHeX itself. I don't really have a proper fix to this, other than reduing the size of all the control elements. I feel like this would break the view on other monitor resolutions though.
Since this seems to be an issue only on a niche part of monitors, I feel like it's better for the impacted users to just use the Tera Finder Launcher instead of the PKHeX Plugins. Eventually users can also adjust the Scale settings for PKHeX itself, which would also have an effect to the Tera Finder plugins.
