### ISSUE TITLE
Latest build for Teal Mask update error:

### ISSUE THREAD

**Issue by GlacierWolf259** [Manu098vm/Tera-Finder#56]
I'm getting this image whenever I try to build the newest version:
![image](https://github.com/Manu098vm/Tera-Finder/assets/75643046/2b2e822c-310c-41e1-8983-67cc19865bb5)

**Comment by foohyfooh** [comment]
My assumption is that they updated the code using a DLL but didn't commit the DLL since they are waiting for the nuget package to be updated so that they can properly link against that.
I made the changes needed to get it working with a compiled DLL in my fork on the branch [230916_no_nuget](https://github.com/foohyfooh/Tera-Finder/tree/230916_no_nuget) if you want to use the latest changes.

**Comment by Manu098vm** [comment]
What @foohyfooh says is accurate.
Little remainder that a download for the latest Tera Finder commit is also available in [GitHub Actions](https://github.com/Manu098vm/Tera-Finder/actions).
