### ISSUE TITLE
TeraFinder.Launcher.dll

### ISSUE THREAD

**Issue by ZombieWolfx** [Manu098vm/Tera-Finder#7]
Malwarebytes is detecting TeraFinder.Launcher.dll as malware on the latest commit.

**Comment by Manu098vm** [comment]
False positive, probably caused by the fact that the program launches other dlls (plugin). To be solved I should probably completely rewrite the app, not something that is worth doing just to solve a false positive. 
If users don't trust the zipped file, they can inspect the source code, and eventually build the program from themself.
Thanks for the report anyways!

**Comment by ZombieWolfx** [comment]
Yeah I figured it had to with dll loadings. No need for rewriting. Thanks!
