### ISSUE TITLE
The progress bar

### ISSUE THREAD

**Issue by maxpong0616** [Manu098vm/Tera-Finder#9]
Hi, I was using the standalond version of the tera finder, and I have to say it works really well!
Just have a little issue that was bothering me, which is the progress bar below the inter face.
![image](https://user-images.githubusercontent.com/67531545/209666719-ea724418-a6fd-4e31-b6a7-479223815406.png)
Since I was running 40 billion times of search at once, and it usually takes a certian bit of time, I would like to see how much it has been done. 
However, the progress bar doesn't seems to be working. Can you have a little check on this? Thanks!

Moreover, I was trying to get a 0 atk 0 spe female shiny indeedee set. But when I searched 40 billion times which two different seeds, I got 2 identical sets from them which only have 2 atk and 0spe. 
I was wondering does that have to do with something that the caculator was build? 
Thanks again for the application!

**Comment by Manu098vm** [comment]
The progress bar has been completely removed from the latest commits since it was slowing down the UI during the calcs by a lot.
It won't be re-added, sadly. I'm working on making all the searches multi-threaded, so they should be lot faster in the future. Updating a GUI element such as the progress bar (or the data grid table) at each calculation would slow down the operations too much. For this reason, the data grid table will be updated only once all the calculations will be completed.

About the Indeedee, if the seeds were different then the calculator is working fine. If there are duplicated seeds, then that's an issue. If the resulting stats/details from those different seeds are the very same, that's just coincidence. The calculations the program does, are the very same the game does to generate a raid pkm. The only difference, is that I use only one xoroshiro rng starting seed, while the game generates a new csprng starting seed every day which is completely unrelated to the previous one. It's possible that two or more xoroshiro seeds close to each other may give similar results.

I will close this issue. Feel free to reopen it if you feel that the indeedee results you got are a bug. In that scenario, i'd suggest to try the latest commit to check if the issue persists.
